name: Full Build

on:
  push:
    branches:
      - main

jobs:
    build-windows:
        runs-on: windows-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.8'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Build EXE with PyInstaller
              run: pyinstaller --onefile --windowed --name=AllumettesGame games/torches/Alumettes.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                    name: windows-executable
                    path: dist/AllumettesGame.exe
        
    build-macos-arm64:
        runs-on: macos-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.8'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip cache purge
                pip install -r requirements.txt --no-cache-dir --index-url https://pypi.org/simple

            - name: Build APP with PyInstaller
              run: pyinstaller --onefile --windowed --name=AllumettesGame --target-arch=arm64 games/torches/Alumettes.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                    name: macos-arm64-executable
                    path: dist/AllumettesGame.app

    build-macos-x86_64:
        runs-on: macos-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.8'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Build APP with PyInstaller
              run: pyinstaller --onefile --windowed --name=AllumettesGame --target-arch=x86_64 games/torches/Alumettes.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                    name: macos-x86_64-executable
                    path: dist/AllumettesGame.app

    build-macos-universal:
        runs-on: macos-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.8'

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Build APP with PyInstaller
              run: pyinstaller --onefile --windowed --name=AllumettesGame --target-arch=universal2 games/torches/Alumettes.py

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                    name: macos-universal-executable
                    path: dist/AllumettesGame.app

    release:
        needs: [build-windows, build-macos-arm64, build-macos-x86_64, build-macos-universal]
        runs-on: ubuntu-latest
        steps:
            - name: Download Windows artifact
              uses: actions/download-artifact@v4
              with:
                    name: windows-executable
                    path: dist/

            - name: Download macOS ARM64 artifact
              uses: actions/download-artifact@v4
              with:
                    name: macos-arm64-executable
                    path: dist/

            - name: Download macOS x86_64 artifact
              uses: actions/download-artifact@v4
              with:
                    name: macos-x86_64-executable
                    path: dist/

            - name: Download macOS Universal artifact
              uses: actions/download-artifact@v4
              with:
                    name: macos-universal-executable
                    path: dist/

            - name: Create release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: dist/*
                name: Release ${{ github.ref_name }}
                generate_release_notes: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
